services:
  redmine:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
      TZ: Asia/Yekaterinburg
    volumes:
      - ./conf.d/database.yml:/usr/src/redmine/config/database.yml
      - ./themes:/usr/src/redmine/public/themes
      - ./plugins:/usr/src/redmine/plugins
      - ./redmine_files:/usr/src/redmine/files